### ISSUE TITLE
Deployment types are not created

### ISSUE THREAD

**Issue by ES-PSH** [Skatterbrainz/CM_Build#32]
The deployment types for all applications are not created. 

I think line 1470 is the issue:
`foreach ($depType in $appSet.deptypes.deptype) {`

I cannot find the $appSet anywhere in the code.

**Comment by Skatterbrainz** [comment]
Please use the CMBuild module rather than this script?  There haven't been any updates or fixes to this in quite a while.  The module was created after this repo and contains many improvements and fixes.
