### ISSUE TITLE
Features installation takes to long

### ISSUE THREAD

**Issue by ManuelMueller1st** [Skatterbrainz/CM_Build#4]
I think you could speed up the process avoiding Install-WindowsFeature & Foreach-Object. Probably using a configuration file or a list of features would be much faster. 

For instantce 
Install-WindowsFeature -Name "BITS,BITS-IIS-Ext,NET-Framework-45-ASPNET,NET-Framework-Core,NET-Framework-Features,NET-WCF-HTTP-Activation45,RDC,RSAT,RSAT-Bits-Server,RSAT-Feature-Tools,WAS,WAS-Config-APIs,WAS-Process-Model,Web-App-Dev,Web-Asp-Net,Web-Asp-Net45,Web-Common-Http,Web-Default-Doc,Web-Dir-Browsing,Web-Filtering,Web-Health,Web-Http-Errors,Web-Http-Logging,Web-Http-Redirect,Web-Http-Tracing,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-Log-Libraries,Web-Metabase,Web-Mgmt-Compat,Web-Mgmt-Console,Web-Mgmt-Tools,Web-Net-Ext,Web-Net-Ext45,Web-Performance,Web-Request-Monitor,Web-Security,Web-Server,Web-Stat-Compression,Web-Static-Content,Web-WebServer,Web-Windows-Auth,Web-WMI"

OR

Install-WindowsFeature -ConfigurationFilePath $PathToXml

**Comment by Skatterbrainz** [comment]
Thank you for the feedback!  Is it really faster to use a config file than the list input?  If it is, I think I would rather have it write the config file on-the-fly (like the SQL and SCCM ini files are now).  I wanted to keep all of the build configuration in one base XML file to avoid having to edit multiple files.  I'll research this more and follow-up.  Thank you!

**Comment by ManuelMueller1st** [comment]
I guess there is not diference in performance beteween the two commands mentioned above. In my testing enviroement it took about 3h building a SCCM Primary Site. The most time consuming task was the prerequisite installation. I'm quite shure the problem is you are using an array, passing every single member of that array to Install-WindowsFeature. In other words:

Install-WindowsFeature -Name "BITS"
Install-WindowsFeature -Name "BITS-IIS-Ext"
Install-WindowsFeature -Name "NET-Framework-45-ASPNET"
and so on

:)

see line 255 and 262

**Comment by Skatterbrainz** [comment]
You are correct.  I don't mean to push back on your suggestion at all.  I was just curious if it processes the config file (XML data) different than it does an array.  I was wondering if it was similar to how Azure works with a JSON template, where it processes all of the nodes in parallel using asynch jobs.  The longest delays I've seen in my testing have been ADK installation (even with cached content), and SQL Server. Although SSMS is pretty darn slow as well.  SCCM is probably the slowest part I've seen though.  I'll test the roles using an external file and see how it impacts performance - thank you for your feedback!!

**Comment by Skatterbrainz** [comment]
I just finished 3 successive tests of the roles.xml file (copied from Niall's downloads at windowsnoob.com) and the times are almost identical.  I'll still add this in 1.1.0 so you can have a choice of either method.  The difference is handled in the cm_build.xml under [payloads].  So if you set the [package] type to "feature" it will run the internal function.  But if the [package] type is set to "payload" it will read the specified external XML file. I'm running one more full site build test and then I'll upload to Github under 1.1.0 branch.  THANK YOU!

**Comment by Skatterbrainz** [comment]
Added in 1.1.1 - the cm_build.xml file contains additional comments to help explain how to use the new capability.
